"""Connect a domain: DNS check -> Let's Encrypt certificate (certbot as a
sibling docker container, webroot challenge) -> nginx server block -> reload.
Renewal runs daily from the scheduler."""
import logging
import os
import re
import socket
import subprocess

import httpx

from . import config, db

log = logging.getLogger("leadfinder.domains")

DOMAIN_RE = re.compile(r"^(?!-)[a-z0-9-]{1,63}(?<!-)(\.(?!-)[a-z0-9-]{1,63}(?<!-))+$")

SITE_TEMPLATE = """# generated by the vps-starter dashboard — do not edit by hand
server {{
    listen 80;
    server_name {names};

    location /.well-known/acme-challenge/ {{
        root /var/www/acme;
    }}
    location / {{
        return 301 https://$host$request_uri;
    }}
}}

server {{
    listen 443 ssl;
    server_name {names};

    ssl_certificate     /etc/letsencrypt/live/{domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{domain}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {{
        proxy_pass http://landing_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }}
}}
"""


class DomainError(Exception):
    """User-facing failure — message is shown in the dashboard."""


def public_ip() -> str:
    if config.PUBLIC_IP:
        return config.PUBLIC_IP
    try:
        with httpx.Client(timeout=10) as client:
            return client.get("https://api.ipify.org").text.strip()
    except httpx.HTTPError as e:
        raise DomainError(
            "Could not determine this server's public IP address."
        ) from e


def _resolves_to_us(host: str, ip: str) -> bool:
    try:
        infos = socket.getaddrinfo(host, 80, proto=socket.IPPROTO_TCP)
    except socket.gaierror:
        return False
    return ip in {info[4][0] for info in infos}


def _docker(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["docker", *args], capture_output=True, text=True, timeout=300
    )


def _reload_nginx() -> None:
    result = _docker("kill", "--signal", "HUP", config.NGINX_CONTAINER)
    if result.returncode != 0:
        raise DomainError(f"Could not reload nginx: {result.stderr.strip()[:300]}")


def _issue_certificate(domain: str, include_www: bool) -> None:
    cmd = [
        "run", "--rm",
        "-v", f"{config.LETSENCRYPT_VOLUME}:/etc/letsencrypt",
        "-v", f"{config.ACME_VOLUME}:/webroot",
        "certbot/certbot", "certonly",
        "--webroot", "-w", "/webroot",
        "--cert-name", domain,
        "-d", domain,
        "-n", "--agree-tos", "--keep-until-expiring",
    ]
    if include_www:
        cmd += ["-d", f"www.{domain}"]
    email = db.get_setting("certbot_email").strip()
    cmd += ["--email", email] if email else ["--register-unsafely-without-email"]
    if config.CERT_STAGING:
        cmd.append("--staging")
    result = _docker(*cmd)
    if result.returncode != 0:
        detail = (result.stderr or result.stdout).strip()[-500:]
        raise DomainError(f"Certificate request failed. Details: {detail}")


def connect(raw_domain: str) -> str:
    """The full flow. Returns a success message; raises DomainError on failure."""
    domain = raw_domain.strip().lower().removeprefix("http://").removeprefix("https://").strip("/")
    domain = domain.removeprefix("www.")
    if not DOMAIN_RE.match(domain):
        raise DomainError(f"'{raw_domain}' doesn't look like a valid domain name.")

    ip = public_ip()
    if not _resolves_to_us(domain, ip):
        raise DomainError(
            f"{domain} doesn't point at this server yet (expected an A record to {ip}). "
            "DNS changes can take a few minutes to spread — save your A record, "
            "wait a bit, and try again."
        )
    include_www = _resolves_to_us(f"www.{domain}", ip)

    _issue_certificate(domain, include_www)

    names = f"{domain} www.{domain}" if include_www else domain
    conf_path = os.path.join(config.NGINX_SITES_DIR, f"{domain}.conf")
    with open(conf_path, "w") as f:
        f.write(SITE_TEMPLATE.format(names=names, domain=domain))
    _reload_nginx()

    db.add_domain(domain, include_www)
    www_note = " (including www)" if include_www else " (www not configured — its A record doesn't point here)"
    return f"https://{domain} is live{www_note}."


def disconnect(domain: str) -> None:
    conf_path = os.path.join(config.NGINX_SITES_DIR, f"{domain}.conf")
    if os.path.exists(conf_path):
        os.remove(conf_path)
        _reload_nginx()
    db.remove_domain(domain)


def renew_certificates() -> None:
    """Daily job — quiet unless something actually renews or fails."""
    if not db.list_domains():
        return
    result = _docker(
        "run", "--rm",
        "-v", f"{config.LETSENCRYPT_VOLUME}:/etc/letsencrypt",
        "-v", f"{config.ACME_VOLUME}:/webroot",
        "certbot/certbot", "renew", "--webroot", "-w", "/webroot", "-q",
    )
    if result.returncode != 0:
        log.warning("certbot renew failed: %s", (result.stderr or result.stdout)[-500:])
        return
    try:
        _reload_nginx()
    except DomainError as e:
        log.warning("%s", e)
